/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCounter: typeof import('./src/components/TheCounter.vue')['default']
    TheFilterBar: typeof import('./src/components/TheFilterBar.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
    TheItem: typeof import('./src/components/TheItem.vue')['default']
    TheModal: typeof import('./src/components/TheModal.vue')['default']
    TheModel: typeof import('./src/components/TheModel.vue')['default']
    TheNav: typeof import('./src/components/TheNav.vue')['default']
    TheOptions: typeof import('./src/components/TheOptions.vue')['default']
    TheSelect: typeof import('./src/components/TheSelect.vue')['default']
    TheTag: typeof import('./src/components/TheTag.vue')['default']
  }
}
